module RuboCop
  module SortedMethodsByCall
    class Plugin < ::LintRoller::Plugin
      def about: -> ::LintRoller::About
      def supported?: (::LintRoller::Context context) -> bool
      def rules: (::LintRoller::Context _context) -> ::LintRoller::Rules
    end
  end
end
